// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBassZSPjUIUawqNWhhnoZTNsLspcPcCf8',
    appId: '1:590743425747:web:4e6a089960fb405de6ba26',
    messagingSenderId: '590743425747',
    projectId: 'instagram-clone-75c52',
    authDomain: 'instagram-clone-75c52.firebaseapp.com',
    storageBucket: 'instagram-clone-75c52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFBBzKuSU0l2eoQMlCYRvjwU-vbNlNHR8',
    appId: '1:590743425747:android:871c48a7feb54e5be6ba26',
    messagingSenderId: '590743425747',
    projectId: 'instagram-clone-75c52',
    storageBucket: 'instagram-clone-75c52.appspot.com',
  );
}
